### PR TITLE
[DOC] Tutorial 1

### PR DESCRIPTION
**Pull request by ReinderVosDeWael**
This PR includes a tutorial .py file which is automatically parsed by Sphinx to create a downloadable tutorial within our ReadTheDocs (see: https://brainstat.readthedocs.io/en/python_tutorial/python/generated_tutorials/plot_tutorial_01_basics.html#sphx-glr-python-generated-tutorials-plot-tutorial-01-basics-py)

### CODE REVIEW

**Comment by sheyma** [comment]
great idea with tutorial documentation!

Let me know if it makes sense to you:
adjusting  my **example.ipynb** in  #82  according to your [Tutorial 01](https://brainstat.readthedocs.io/en/python_tutorial/python/generated_tutorials/plot_tutorial_01_basics.html#sphx-glr-python-generated-tutorials-plot-tutorial-01-basics-py).

**Comment by ReinderVosDeWael** [comment]
@sheyma  what are your thoughts on the current version https://brainstat.readthedocs.io/en/python_tutorial/python/generated_tutorials/plot_tutorial_01_basics.html#sphx-glr-python-generated-tutorials-plot-tutorial-01-basics-py. I haven't added visualization yet (is the vis branch ready for review?), so pretend that all the prints are actually beautiful images of data on the hemispheres. The structure is largely the same as your tutorial. The main differences are:

- No initial hemisphere visualization; I'd give this its own tutorial once we finish the vis branch.
- Added an interaction effect to the model
- Used all that Sphinx goodness to include links to our API as well as those of packages used.

**Comment by PeerHerholz** [comment]
Quick question re the tutorial: during one meeting in the distant past, we talked about "interactive aspects", e.g. a `binder` link, etc., but also maybe a `jupyter book`. The way I see/understand things ATM, the examples in the docs would be "classic" usage examples showcasing the `API` which could get a link to an interactive instance. A tutorial, comparable to the classic `SurfStat` one however could be its own `jupyter book` given that it would have more background information and be more like a lecture. WDYT? Looping in @MICA-MNI and @sofievalk.

**Comment by ReinderVosDeWael** [comment]
So what's not clear to me is why wouldn't we use the Jupyter notebook that's available here.

**Comment by ReinderVosDeWael** [comment]
In other words could we link binder and the ReadThedocs

**Comment by ReinderVosDeWael** [comment]
Something like #97 as visible in https://mybinder.org/v2/gh/MICA-LAB/BrainStat/python_tutorial_binder?filepath=docs%2Fpython%2Fgenerated_tutorials%2Fplot_tutorial_01_basics.ipynb

**Comment by PeerHerholz** [comment]
Yeah, we could just use the noteboos and include `binder` links, for example as done [here](https://nibetaseries.readthedocs.io/en/stable/auto_examples/plot_run_nibetaseries.html#sphx-glr-download-auto-examples-plot-run-nibetaseries-py). I think my question was rather a conceptual one wrt content.

**Comment by ReinderVosDeWael** [comment]
Oh the way NiBetaSeries implemented it is kinda cool... I'm taking notes here :p. Personally I don't see much reason to have different content in the interactive binder and the static tutorials, especially if we can link them up as nicely as is done in NiBetaSeries. I'd definitely be for providing this in a more "expanded" format though.

**Comment by ReinderVosDeWael** [comment]
New push adds the binder links - for now they are linked to this branch but this should be changed to master before merging.

**Comment by PeerHerholz** [comment]
Sorry, I think my question was misleading. The static tutorials in RTD should definitely include a link that brings users to the corresponding interactive version. What I meant was a potential differentiation between tutorials with API showcases and a more in-depth version basically constituting a little workshop that also includes more background information concerning random field theory and models. This could be outside the `brainstat` docs as its own thing.

**Comment by ReinderVosDeWael** [comment]
Right, OK, yes I think we may have misunderstood each other. Yes I'd fully agree with that.

**Comment by ReinderVosDeWael** [comment]
@PeerHerholz The current binder link results in an error (see: https://mybinder.org/v2/gh/MICA-LAB/BrainStat/python_tutorial?filepath=docs/python/tutorials/plot_tutorial_01_basics.py) would you have an idea how to fix this? Google isn't entirely helpful here.

**Comment by PeerHerholz** [comment]
How did you build it? If I build it via binder it seems to work: [Binder](https://mybinder.org/v2/gh/MICA-LAB/BrainStat/4f0b792e06a940a54e44d1953a776cc0e2b9b1e9).

We would need to add [jupytext](https://github.com/mwouts/jupytext) as done for example over in [brainspace](https://github.com/PeerHerholz/BrainSpace/tree/notebook_binder_support) so that `py` files open as `notebooks`.

**Comment by ReinderVosDeWael** [comment]
The link I provided was simply the binder link automatically generated in the tutorial ReadTheDocs page. I'm not sure what you mean by "add jupytext". I tried converting from a ipynb to py with jupytext in two ways in the last commits but neither seems to work on mybinder.

**Comment by ReinderVosDeWael** [comment]
For future reference: Binder integration was disabled (commented out in conf.py, other associated files removed). Binder integration will continue on another PR.

**Pull request merged**
