### PR TITLE
Tutor

### PR DESCRIPTION
**Pull request by sheyma**
this is the primitive but fully working version of python BrainStat tutorial.

### CODE REVIEW

**Comment by sheyma** [comment]
**tutor** is rebased on **BrainStat_name**

**Comment by ReinderVosDeWael** [comment]
I was running through this tutorial to look at the visualization scripts and ran into the following issues:

- Parula colormap is defined after usage. 
- No module named 'nilearn._utils.compat'. (During import)
- When using nb.frreesurfer.io.read_label there's a hardcoded path - all subsequent code that relies on this I couldn't execute. 

Also are the parula values here a direct copy from MATLAB? The parula colormap is proprietary. Whether Mathworks would pursue copyright claims based on this is, as far as I'm aware, untested, but I wouldn't want to be the one to try it out.

**Comment by sheyma** [comment]
Thanks for the review! Let's keep this PR not-merged for a while, since **1**. we will do the refactoring/renaming and **2**. tidy up plotting functions. After all, I will re-base it and re-build it.


> Parula colormap is defined after usage.

please feel free to use any colormap that you think it's proper.

> No module named 'nilearn._utils.compat'. (During import)

I haven't really faced with this problem. 
Here is my nilearn version, maybe you could also try it with that:

`nilearn                   0.7.0
`

> When using nb.frreesurfer.io.read_label there's a hardcoded path - all subsequent code that relies on this I couldn't execute.

Eye-balling on the usage of read_label, it uses two files that are already located in fsaverage5 directory:

[fsaverage5/](https://github.com/MICA-MNI/BrainStat/tree/tutor/surfstat/tutorial/fsaverage5
)

**Comment by ReinderVosDeWael** [comment]
I've started building a tutorial on ReadTheDocs (#81). I suggests we pull parts of this tutorial into that, rather than continue on this rather outdated branch.

**Comment by sheyma** [comment]
yes, all makes sense.
Let me delete this PR.

**Pull request closed without merging**
