### PR TITLE
Pipbranch

### PR DESCRIPTION
**Pull request by sheyma**
Hi,
here is the first step of building a python package via `$ pip install`.
Of note, it is rebased on **[unittests](https://github.com/MICA-LAB/BrainStat/pull/55)** branch, which we have not merged into master yet.

Usage:  `$ python setup.py install`

Best would be to generate distribution packages for the BrainStat, so that anyone can do  `$ pip install brainstat`

Cheers!

### CODE REVIEW

**Comment by ReinderVosDeWael** [comment]
@OualidBenkarim @PeerHerholz Can either of you have a look? I have no idea how to set up a proper Python package install.

**Comment by sheyma** [comment]
Yes, any review here is appreciated.
this was my reference preparing that, if it helps:
https://packaging.python.org/tutorials/packaging-projects/

**Comment by PeerHerholz** [comment]
Ahoi hoi folks,

sorry for the late reply. 
Based on the files and tests I could check things seem to be ok/working. Overall, I would have suggested to adapt these aspects from the `brainspace` repo anyway... A few things that came to my mind:

- introducing a `setup.cfg` and a `CHANGELOG.txt` file
- the `setup.py` could be extended with further important information as e.g. seen in the [brainspace equivalent](https://github.com/MICA-MNI/BrainSpace/blob/master/setup.py), especially: 
    - specific version numbers of install requirements
    - supported `python` versions

@sheyma did you test the packaging and subsequent installation as described in the resource you shared?

**Comment by sheyma** [comment]
short answer: what we have in ` requirements.txt` are all checked with python **3.5, 3.6, 3.7, 3.8**. 

Let me study your other review points now.

**Comment by ReinderVosDeWael** [comment]
I suggest dropping Python 3.5 from the supported versions as it has already reached its official end-ofl-life (https://www.python.org/dev/peps/pep-0478/)

**Comment by sheyma** [comment]
okidoki @PeerHerholz ,

- `setup.py` content is now extended based on `brainspace`.

- `setup.cfg` is added.

- ` CHANGELOG.txt` : I would postpone adding this until **brainstat** is more stable.

Cheers!

**Comment by sheyma** [comment]
.... wait, README.md content looks ugly.

**Comment by sheyma** [comment]
now it should be fine.

**Comment by PeerHerholz** [comment]
Ahoi hoi,

thx @sheyma, looks great!
One last question: is there a specific reason not all `requirements` have a specific version? IIRC some functions of `nibabel`, `pandas` and `scikit-learn` can vary quite drastically between versions.

**Comment by sheyma** [comment]
ohhh yes, there was a reason for avoiding package version specifications for `nibabel`, `pandas` and `scikit-learn`.

The original existing version specifications in `requirements.txt`, did not work for for all python versions. For instance, nibabel x.y and pandas a.b works in python 3.6 together but not in python 3,5, and many similar issues. However, the way it is defined now, all works (tested in azure, travis, git actions).

That's why I removed all not-needed versioning. I would recommend to add version restrictions only for validated incompatibilities. (You are more than welcome to test it @PeerHerholz.) 

The next PR on top would be anyway adding it to pypi and test again with `$pip install.`

**Comment by ReinderVosDeWael** [comment]
This is likely due to 3.5 no longer being supported so I wouldn't make decisions based on 3.5 (or earlier) incompatibilities.

**Comment by sheyma** [comment]
**3.5** was just an example.

**Comment by PeerHerholz** [comment]
Ahoi hoi,

yeah...version incompatibilities...always fun. If things work out within the tests we could continue here. However, I would definitely keep those things in mind, especially certain cross-dependencies (e.g. `nibabel` and `nilearn`).

**Pull request merged**
