### PR TITLE
Unittests

### PR DESCRIPTION
**Pull request by sheyma**
Hi, 
this PR contains pure python tests for the BrainStat (143 pieces ;) ), ie. completely matlab-independent. 

Usage: 

`BrainStat/surfstat $ python -m pytest tests/unit_*
`

Downsides: input and expected-output test data is far too large (all in `/BrainStat/surfstat/tests/data/unitdata`) to be merged in master. Potential solutions: Minimizing the amount of data or having an extra optional git repo, that contains the data for expensive tests only (as I saw other projects doing that).

### CODE REVIEW

**Comment by ReinderVosDeWael** [comment]
Just one quick comment (will look more closely later this week): I recommend we move away from the following lines of code:

```
import sys
sys.path.append("python")
import something.something
```
and, more importantly, lines like this one:
```
infile  = './tests/data/unitdata/statedg_05_IN.pkl'
```

Both of these rely on a particular working directory which is asking for trouble. Moreover the latter will error on Windows due to the difference in file separators. 

For fixing both of these I recommend we wait until the refactoring is done and rebase. Then for the former code snippet we can replace it with something like `from brainstat.submodule import something`  For the latter, I resolved this in the refactoring PR as follows:

```
import os
import brainstat

data_dir = (os.path.dirname(brainstat.__file__) + 
        os.path.sep + 'tests' + os.path.sep + 'data' + os.path.sep + 'volfiles'
        + os.path.sep)

```

This should work on any operating system no matter what the current working directory is.

**Comment by ReinderVosDeWael** [comment]
Could you add comments to the tests showing what's different between them? If one or a few of them were to error I wouldn't be able to tell what differentiates these from the other tests without going into every data file.

**Comment by sheyma** [comment]
Allright, main changes:

- we have now purely pythonic tests at **/BrainStat/brainstat/tests**
- test data dir is defined globally in **testutil.py**
- pytest runs now in any location under **/BrainStat/**, just like `$ pytest`

Downside:
- test data is quite large, about 261M. We might consider chopping it later.

Cheers!

**Comment by ReinderVosDeWael** [comment]
Mhm I'll have a close look at it later this week. 261Mb is definitely far too large; we'll have to downsize that substantially.

**Comment by ReinderVosDeWael** [comment]
I created a PR for this one that zips all the data files. It's no replacement for have a closer look at the current data management, but it does already save a substantial amount of space.

**Comment by sheyma** [comment]
Commentary added for each test data in each test function.

**Review by ReinderVosDeWael — CHANGES_REQUESTED** [review]
Thanks for the additional comments. However, what I think we need here is a comment stating _why_ each test is run, rather than the specifics of the input data. What does each test do that isn't covered by the prior ones? For some input types this is obvious, but from just the variables it seems like there's several tests that essentially test identical things. 

One issue that pops up quite a few times are tests with input data that should never occur. See specific examples below, but I think we should add a few error checks and remove/alter these tests. 

Also it may be helpful to include code coverage tools with this PR. If you want I can set some up. 

Specific comments: 

- Why all the changes to relative imports? These are discouraged by PEP8 standards: "Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path):" (https://www.python.org/dev/peps/pep-0008/)
- SurfStatEdg tests 4 and 5 appear to test identical parameters. Can we remove one of them?
- Are the original MATLAB/Python tests completely removed? I recommend we still keep these for testing cross-language differences after future changes. 
- Can SurfStatNorm tests 2 and 3 be derived from the same input file?
- I haven't gone into the data files to check each case, but at least some of the tests in SurfStatP test nonsensical input data e.g. test 1 has data for one vertex (see slm['t']) but many vertices (see slm['tri']). The correct output here should be an error, rather than any numeric output. I suggest we alter the function to throw an error for non-sensical input and remove tests broken by these changes.
- It's not clear to me what the intent is behind the different SurfStatF tests. 
- How do the following groups in SurfStatLinMod test different things? Test 1/2, 3/4/6/7, 8/9, 10/11.
- SurfStatLinMod doesn't use coordinate information, so tests with the 'coord' parameter can be removed. 
- SurfStatPeakClus tests 2/3/4 have non-sensical input i.e. data for more vertices than exist. Similar to SurfStatP, I recommend we modify the function to throw an error for such input and remove the tests. 
- Are SurfStatPeakClus 8/9/14 different in any important manner?
- I suspect many of the input data in SurfStatPeakClus have difference in the vertices for which data exists, and vertices on the mesh (e.g. test 17, 18, 20). 
- Are SurfStatQ tests 1/2/3 testing different things?
- SurfStatQ 7 has the vertex-data vertex-number issue. 
- There's several SurfStatQ tests with input data that is unused by the function. The only inputs used by SurfStatQ are: t, df, k, dfs, resl, tri, lat. 
- In SurfStatResels, can the input data of tests 6/7/8 be combined into one file? 
- What does SurfStatResels test 9 do that isn't covered by test 8? 
- Can the input data of SurfStatResels tests 10/11/12 be combined into one file? Also to reduce data size we could use a smaller surface; this one is quite big for a unit test.
- Input to SurfStatSmooth tests 1, 3 are nonsensical (see before). 
- Test 3 of SurfStatT has input variables that are unused by the function; see the function comments for the list of used variables.

**Comment by rudimeier** [comment]
__Regarding relative imports__ (this patch was from me).

PEP 8 speaks only against _implicit_ relative imports,  but nothin bad about the _explicit_ ones. (The _implicit_ ones do not even work anymore in Python 3, so this can't be done wrong right now):

"However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose:"

Also interesting: "Standard library code should avoid complex package layouts and always use absolute imports."

I decided to go with _explicit relative_ imports as I think your planned directory structure _is quite complex_. Using relative imports inside sub packages, is more invariant, regarding future renaming, and re-structuring. The way I handled the imports was directly taken from the official tutorial:   https://docs.python.org/3/tutorial/modules.html#intra-package-references

**Comment by sheyma** [comment]
amazing review! I will do my best to address all your points @ReinderVosDeWael . Thanks!

**Comment by sheyma** [comment]
Hi @ReinderVosDeWael,


when I initially created all these tests, I was following the naive approach, to simply hardcoding formerly random input/results of our original matlab tests (in .pkl files). Now I realized that this was not the very best approach, e.g. too big, too slow, hardly self-explanatory, as you also pointed out in your review comments.
 
I'd like to fix these issues in a separate PR, that focuses on optimizing tests with the points above. I'd really appreciate, if we could still merge this PR into master, as this is the first working version of our unittests.

**Comment by ReinderVosDeWael** [comment]
We'll have to optimize these unit tests a lot more before we merge them into master. Once we inevitably switch to Azure, we have 1800 minutes of runtime per month (remember: we're currently running on trial credits with Travis, once they run out TravisCI will always fail). Current unit test run time seems to be about 8 minutes per implementation (https://travis-ci.com/github/MICA-LAB/BrainStat/builds/210629589) for a total of 32 runtime minutes across 4 Python versions. That comes down 56.25 commits per month before our CI simply stops working for the month. That seems like far too few commits to me.

**Comment by ReinderVosDeWael** [comment]
Alternatively if the Python CI is performed in Github actions (which has basically no usage limits) then it'd circumvent the current build duration issue.

**Pull request merged**
